---

  - include: sbt_0.13.1.yml

  - name: API | Create dir
    file: dest=$uys_boldface_install_dir owner=$ansible_ssh_user group=admin mode=755 state=directory
    sudo: yes
    tags: api

  - name: API | Checkout
    git: repo=$uys_boldface_repo dest=$uys_boldface_install_dir version=master
    register: checkout
    tags: api

  - name: API | Change ownership of checkout directory
    sudo: yes
    action: shell chown -R $ansible_ssh_user:admin {{uys_boldface_install_dir}}

  - name: API | Copy upstart script
    action: template src=upstart.conf.j2 dest=/etc/init/boldface.conf
    register: upstart
    sudo: yes
    tags: api

  - name:  API | Generate start script
    action: command chdir=$uys_boldface_install_dir sbt stage
    when: checkout.changed
    sudo: yes
    tags: api
    notify: API | Restart boldface

