---
- name: Install Mysql package
  action: $ansible_pkg_mgr pkg={{item}}  state=present
  with_items:
   - mysql-server

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=true
